[versions]
minecraft = "1.20.2"
parchment_minecraft = "1.20.1"
parchment_mappings = "2023.08.20"

neoforge = "20.2.8-beta"

fabric_loader = "0.14.24"
fabric_api = "0.90.7+"

mdg_plugin = "1.4.1"
mdg_dsl = "1.5.1"
autoservice = "1.1.1"

fabric_loom = "1.4.4"
quilt_licenser = "2.0.1"

neogradle = "7.0.8"
#librarian = "1.2.0"

jetbrains_annotations = "24.0.1"
jspecify = "0.3.0"

managedversioning = "1.0.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }

[plugins]

managedversioning = { id = "dev.lukebemish.managedversioning", version.ref = "managedversioning" }
mdg_plugin = { id = "org.groovymc.modsdotgroovy", version.ref = "mdg_plugin" }
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
quilt_licenser = { id = "org.quiltmc.gradle.licenser", version.ref = "quilt_licenser" }
neogradle_userdev = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }
neogradle_mixin = { id = "net.neoforged.gradle.mixin", version.ref = "neogradle" }
#librarian = { id = "org.parchmentmc.librarian.forgegradle", version.ref = "librarian" }
